export const UPDATE_MASTER_VOLUME = "UPDATE_MASTER_VOLUME";
export const SHOW_APP = "SHOW_APP";
export const SET_WIFI_STATUS = "SET_WIFI_STATUS";
export const SET_WIFI_LIST = "SET_WIFI_LIST";
export const SET_WIFI_ERROR = "SET_WIFI_ERROR";
export const SHOW_SECURITY_PAGE = "SHOW_SECURITY_PAGE";
export const CLEAR_SECURITY_PAGE = "CLEAR_SECURITY_PAGE";
export const STORE_OS_INFO = "STORE_OS_INFO";